### ISSUE TITLE
v0.5.4 crashes just after the start on Win 10 Pro

### ISSUE THREAD

**Issue by HostFat** [mailchuck/PyBitmessage#124]
The previews one (v0.5.3) was working.

2015-11-24 01:29:06,223 - CRITICAL - PyBitmessage requires PyQt unless you want to run it as a daemon and interact with it using the API. You can download it from http://www.riverbankcomputing.com/software/pyqt/download or by searching Google for 'PyQt Download' (without quotes).
Traceback (most recent call last):
  File "C:\Users\John Doe\Documents\src\PyInstaller-2.1\bitmessagemain\build\bitmessagemain\out00-PYZ.pyz\bitmessageqt", line 14, in <module>
  File "C:\Users\John Doe\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 409, in load_module
ImportError: DLL load failed: The operating system cannot run %1.

**Comment by PeterSurda** [comment]
That looks odd. Try to install PyQT and see if it helps.

**Comment by HostFat** [comment]
I've downloaded and installed this one: PyQt4-4.11.4-gpl-Py3.4-Qt5.5.0-x64.exe

Now it works, but I didn't need to install anything else before.

**Comment by PeterSurda** [comment]
ok but at least now I know a bit more

**Comment by PeterSurda** [comment]
I made a clean build and reuploaded the binary. I don't know if that helps but we'll see. Other people are reporting problems too.

**Comment by HostFat** [comment]
I try to uninstall what I've installed, and try again with the new binary.

Is it already up?

**Comment by PeterSurda** [comment]
Yea it should be up. What's your OS?

**Comment by HostFat** [comment]
Again.
My OS is Windows 10 Pro. As I said the v0.5.3 was working without any problem.

I've downloaded it again from here https://github.com/mailchuck/PyBitmessage/releases

2015-11-24 02:05:21,914 - CRITICAL - PyBitmessage requires PyQt unless you want to run it as a daemon and interact with it using the API. You can download it from http://www.riverbankcomputing.com/software/pyqt/download or by searching Google for 'PyQt Download' (without quotes).
Traceback (most recent call last):
  File "C:\Users\John Doe\Documents\src\PyInstaller-2.1\bitmessagemain\build\bitmessagemain\out00-PYZ.pyz\bitmessageqt", line 14, in <module>
  File "C:\Users\John Doe\Documents\src\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 409, in load_module
ImportError: DLL load failed: The operating system cannot run %1.

**Comment by PeterSurda** [comment]
That PyQT version is not the correct one anyway (it should be qt4 for python 2.7). What's language do you use in your OS?

**Comment by HostFat** [comment]
English.

I tried to download and install this:
PyQt4-4.11.4-gpl-Py2.7-Qt4.8.7-x64.exe

Even with this one it works/starts correctly.

**Comment by PeterSurda** [comment]
can you try to verify the pgp signature on the downloaded file?

**Comment by HostFat** [comment]
Too late now... Maybe tomorrow I'll find a way.

**Comment by PeterSurda** [comment]
I rebuilt the binary on Windows 2008 and MinGW for a 32bit architecture. I tested it on Windows 2008 (32bit), Windows 8 and Windows 10 (64bit). There are no more warnings, just the bitmsghash performance appears to be slower. Let me know how it works out for you.

**Comment by HostFat** [comment]
Yes. It seems working perfectly :)

**Comment by PeterSurda** [comment]
Excellent.
