### ISSUE TITLE
logging rollover on windows

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#77]
Logged from file shared.py, line 364
2015-10-28 20:24:53,181 - INFO - Flushing inventory in memory out to disk...
Traceback (most recent call last):
  File "C:\Program Files\Python 2.7.10\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Program Files\Python 2.7.10\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file shared.py, line 367

**Comment by PeterSurda** [comment]
Not a high priority, I use different logging setup as well.
